### ISSUE TITLE
GitHub显示失败但实际打卡成功，这是GitHub提出的问题

### ISSUE THREAD

**Issue by zephyryun** [Lin1031/izhicheng#6]
![image](https://user-images.githubusercontent.com/93637111/208145284-c58ae11b-b11a-4052-9459-2518eed89c3a.png)

**Comment by Lin1031** [comment]
抱歉现在才看到问题。请检查一下actions中的学号，最后一行是否有删除，就是输入完最后一个学号之后不要回车。
